[General]
ned-path = HOME/raynet/_topologies:HOME/inet4.5/examples:HOME/inet4.5/showcases:HOME/inet4.5/src:HOME/inet4.5/tests/validation:HOME/inet4.5/tests/networks:HOME/inet4.5/tutorials:HOME/omnetpp/samples/tcpPaced/src:HOME/omnetpp/samples/tcpGoodputApplications/src:HOME/omnetpp/samples/cubic/src:HOME/raynet/simlibs/RLComponents/src:HOME/raynet/simlibs/Orca/src:


# Outputs/verbosity
check-signals = false
record-eventlog= false
cmdenv-express-mode = true
cmdenv-redirect-output = false
cmdenv-log-prefix = %t | %m |
cmdenv-silent = true
cmdenv-event-banners = false
**.cmdenv-log-level = off
**.queue.recordStats = false

# Metrics (for plotting!)
**.scalar-recording=false
**.vector-recording=false
**.bin-recording=false

# Network parameters
network = topologies.Dumbbell
**.numberOfFlows = 1                                                # Number of client/server pairs. Includes the "main" protocol being tested, client[0]
**.router1.ppp[0].queue.dataCapacity = ORCA_BOTTLENECK_BUFFER_SIZE  # Bottleneck buffer size
**.bottleneckDatarate = ORCA_BOTTLENECK_BW                          # Bottleneck bandwidth
**.bottleneckDelay = ORCA_BASE_RTT                                  # Base RTT

**.goodputInterval = 1s
**.throughputInterval = 1s

**.client[0].tcp.typename = "OrcaTcp"			# Orca; Custom TCP version must be used to make Orca visible and allow use of custom parameters
**.client[0].tcp.tcpAlgorithmClass = "Orca"		# Orca; correct algo must be selected

**.tcp.advertisedWindow = 200000000
**.tcp.windowScalingSupport = true
**.tcp.windowScalingFactor = -1
**.tcp.increasedIWEnabled = true
**.tcp.delayedAcksEnabled = false
**.tcp.timestampSupport = true
**.tcp.ecnWillingness = false
**.tcp.nagleEnabled = true
**.tcp.stopOperationTimeout = 4000s
**.tcp.mss = 1448
**.tcp.sackSupport = true

# Client settings
*.client[*].numApps = 1
*.client[*].app[0].typename  = "TcpSessionApp" #"TcpGoodputSessionApp"
*.client[*].app[0].sendBytes = 2GB
*.client[*].app[0].dataTransferMode = "bytecount"
*.client[*].app[0].statistic-recording = false
**.client[*].app[*].connectAddress = "server["+string(parentIndex())+"]"
**.client[*].app[*].tOpen  = 0s
**.client[*].app[*].tSend = 0s
**.client[*].app[*].tClose = -1s

# Queue settings
**.ppp[*].queue.typename = "DropTailQueue"

# Server settings
**.server[*].numApps = 1
**.server[*].app[0].typename  = "TcpSinkApp"
#**.server[*].app[0].serverThreadModuleType = "tcpgoodputapplications.applications.tcpapp.TcpGoodputSinkAppThread"


# Orca Parameters
**.rewardDelayForgiveness = 1.25        # How much delay increases should be forgiven/ignored in reward calculation
**.rewardLossMultiplier = 5             # How strongly loss should affect reward calculation
**.printDebugMessages = false           # set to true to print debug messages for the CC algorithm
**.takeActions = true                  # If false, will stop Orca from performing actions
**.maxRLSteps = MAX_RL_STEPS            # Steps before a given agent's simulation is reset
**.fixedIntervals = true                # Interval lengths should be fixed
**.fixedIntervalDuration = .02          # Monitor interval duration in seconds. Still used as initial intervalDuration if not using fixed intervals.
debug-on-errors = true
