# ! SET YOUR ENVIRONMENT VARIABLES HERE ! #
export RAYNET_PATH=$HOME/raynet
export OMNET_PATH=$HOME/omnetpp
export INET_PATH=$OMNET_PATH/samples/inet4.5

export RAYNET_VENV_PATH=$RAYNET_PATH/.venv
# ! BUILD WILL FAIL IF THESE ARE INCORRECT ! #