[General]
ned-path = !HOME!/raynet/_topologies:!HOME!/inet4.5/examples:!HOME!/inet4.5/showcases:!HOME!/inet4.5/src:!HOME!/inet4.5/tests/validation:!HOME!/inet4.5/tests/networks:!HOME!/inet4.5/tutorials:!HOME!/omnetpp/samples/tcpPaced/src:!HOME!/omnetpp/samples/tcpGoodputApplications/src:!HOME!/omnetpp/samples/cubic/src:!HOME!/raynet/simlibs/RLComponents/src:!HOME!/raynet/simlibs/Orca/src:!HOME!/raynet/simlibs/Astraea/src:!HOME!/raynet/simlibs/CleanSlate/src:

**.scenarioManager.script = xmldoc("!SCENARIO!") # used to modify the bottleneck link over time.

# Outputs/verbosity
check-signals = false
record-eventlog= false
cmdenv-express-mode = true
cmdenv-redirect-output = false
cmdenv-log-prefix = %t | %m |
cmdenv-silent = true
cmdenv-event-banners = false
**.cmdenv-log-level = off
**.queue.recordStats = false

# Metrics (for plotting!)
**.scalar-recording=false
**.vector-recording=false
**.bin-recording=false

# Network parameters
network = topologies.Dumbbell
**.numberOfFlows = !FLOWS!                                          # Number of client/server pairs. Includes the "main" protocol being tested, client[0]
**.router1.ppp[0].queue.dataCapacity = !QSIZE!  # Bottleneck buffer 
**.bottleneckDatarate = !BW!                          # Bottleneck bandwidthsize
**.bottleneckDelay = !DELAY!                                  # Base RTT

**.goodputInterval = 1s
**.throughputInterval = 1s

**.tcp.advertisedWindow = 200000000
**.tcp.windowScalingSupport = true
**.tcp.windowScalingFactor = -1
**.tcp.increasedIWEnabled = true
**.tcp.delayedAcksEnabled = false
**.tcp.timestampSupport = true
**.tcp.ecnWillingness = false
**.tcp.nagleEnabled = true
**.tcp.stopOperationTimeout = 4000s
**.tcp.mss = 1448
**.tcp.sackSupport = true

# Client settings
*.client[*].numApps = 1
*.client[*].app[0].typename  = "TcpSessionApp" #"TcpGoodputSessionApp"
*.client[*].app[0].sendBytes = 2GB
*.client[*].app[0].dataTransferMode = "bytecount"
*.client[*].app[0].statistic-recording = false
**.client[*].app[*].connectAddress = "server["+string(parentIndex())+"]"
**.client[*].app[*].tOpen  = 0s
**.client[*].app[*].tSend = 0s
**.client[*].app[*].tClose = -1s

# Queue settings
**.ppp[*].queue.typename = "DropTailQueue"

# All agents use the same protocol
**.client[*].tcp.typename = "!PROTOCOL!Tcp"
**.client[*].tcp.tcpAlgorithmClass = "!PROTOCOL!"

# Servers - all raynet agents used TcpPaced, so cubic is a good fit for servers
**.server[*].numApps = 1
**.server[*].app[*].typename = "TcpSinkApp"
**.server[*].tcp.typename = "TcpPaced"
**.server[*].tcp.tcpAlgorithmClass = "TcpCubic"

# Logging
**.printDebugMessages = true            # set to true to print debug messages for the CC algorithm
**.takeActions = true                  # If false, will stop Astraea from performing actions
debug-on-errors = true
