
[General]
ned-path = HOME/inet4.4/src/inet:HOME/inet4.4/examples:HOME/raynet/simlibs/RLComponents/src:HOME/raynet/simlibs/JamesLib/src


check-signals = false
record-eventlog= false
cmdenv-express-mode = true
record-eventlog=false
cmdenv-redirect-output = false
cmdenv-output-file = dctcpLog.txt
**.client*.tcp.conn-8.cmdenv-log-level = detail
cmdenv-log-prefix = %t | %m | %s


cmdenv-event-banners = false
**.cmdenv-log-level = off


**.**.tcp.conn-*.cwnd:vector(removeRepeats).vector-recording = true
**.**.tcp.conn-*.rtt:vector(removeRepeats).vector-recording = true
**.**.tcp.conn-*.srtt:vector(removeRepeats).vector-recording = true
**.**.tcp.conn-*.throughput:vector(removeRepeats).vector-recording = true
**.**.tcp.conn-*.**.result-recording-modes = vector(removeRepeats)
**.**.queue.queueLength:vector(removeRepeats).vector-recording = true
**.**.queue.queueLength.result-recording-modes = vector(removeRepeats)
**.**.goodput:vector(removeRepeats).vector-recording = true
**.**.goodput.result-recording-modes = vector(removeRepeats)
**.**.bandwidth:vector(removeRepeats).vector-recording = true
**.**.bandwidth.result-recording-modes = vector(removeRepeats)
**.**.mbytesInFlight:vector(removeRepeats).vector-recording = true
**.**.mbytesInFlight.result-recording-modes = vector(removeRepeats)
**.scalar-recording=false
**.vector-recording=true
**.bin-recording=false 
cmdenv-silent = false

numberOfFlows = 5
network = JamesLib.JamesNet

# Clients
**.client[*].numApps = 1
**.client[*].app[*].typename  = "TcpSessionApp"
**.client[*].app[*].active = true
**.client[*].app[*].connectAddress = "server["+string(parentIndex())+"]"
**.client[*].app[*].tOpen  = 0.0s
**.client[*].app[*].tSend = 0.0s
**.client[*].app[*].sendBytes = 2GB

# TCP

# Everyone defaults to standard TCP
**.client[0].tcp.typename = "RLTcp"
**.client[0].tcp.tcpAlgorithmClass = "JamesCC"


**.tcp.advertisedWindow = 200000000
**.tcp.windowScalingSupport = true
**.tcp.windowScalingFactor = -1
**.tcp.increasedIWEnabled = true
**.tcp.delayedAcksEnabled = false
**.tcp.timestampSupport = true
**.tcp.ecnWillingness = false
**.tcp.nagleEnabled = true
**.tcp.stopOperationTimeout = 4000s
**.tcp.mss = 1448
**.tcp.sackSupport = true

# RLTcp variables?
**.maxWindow = 10              # maximum window size 
**.stateSize = 4               # dimension of the state space
**.maxObsCount = 15                # max number of observations for a single state
**.ewmaWeight = 1.5                # weight for the moving average of state variables (as in Tcp-Ex Machina)
**.delayWeightReward = 15.2        # weight for throughput vs. delay trade-off
**.printDebugMessages = false      # set to true to print debug messages for the CC algorithm
**.maxRLSteps = 1000      # set to true to print debug messages for the CC algorithm

# Servers
**.server[*].numApps = 1
**.server[*].app[*].typename = "TcpSinkApp"

# Routers
**.router1.ppp[*].queue.packetDropped = true
**.router2.ppp[*].queue.recordDrop = true
**.router1.ppp[*].queue.typename = "DropTailQueue"
**.router2.ppp[*].queue.typename = "DropTailQueue"

**.queue.recordStats = false
**.ppp[*].queue.packetCapacity = 40
