
[General]
ned-path = /home/cjuknowles/inet4.4/src/inet:/home/cjuknowles/inet4.4/examples:/home/cjuknowles/raynet/simlibs/RLComponents/src:/home/cjuknowles/raynet/simlibs/JamesLib/src


check-signals = false
record-eventlog=true
cmdenv-express-mode = false
# cmdenv-output-file = jamesLog.txt
debug-on-errors = true
print-undisposed = true
#cmdenv-log-prefix = %l %J | #the prefix of a log statement line. Symbols in manual.
**.vector-recording = true#true
**.scalar-recording = true#true
**.bin-recording = true#true
**.statistic-recording = true#true
**.cmdenv-log-level = debug

network = JamesLib.JamesNet

**.numberOfFlows = 1

# Clients
**.client[*].numApps = 1
**.client[*].app[*].typename  = "TcpSessionApp"
**.client[*].app[*].active = true
**.client[*].app[*].connectAddress = "server["+string(parentIndex())+"]"
**.client[*].app[*].tOpen  = 0.0s
**.client[*].app[*].tSend = 0.0s
**.client[*].app[*].sendBytes = 2GB

# TCP
# **.tcp.typename  = "RLTcp"
**.tcp.tcpAlgorithmClass = "TcpNewReno"
**.tcp.advertisedWindow = 200000000
**.tcp.windowScalingSupport = true
**.tcp.windowScalingFactor = -1
**.tcp.increasedIWEnabled = true
**.tcp.delayedAcksEnabled = false
**.tcp.timestampSupport = true
**.tcp.ecnWillingness = false
**.tcp.nagleEnabled = true
**.tcp.stopOperationTimeout = 4000s
**.tcp.mss = 1448
**.tcp.sackSupport = true

# RLTcp variables?
#**.tcp.maxWindow = 10              # maximum window size 
#**.tcp.stateSize = 8               # dimension of the state space
##**.maxObsCount = 15                # max number of observations for a single state
#**.ewmaWeight = 1.5                # weight for the moving average of state variables (as in Tcp-Ex Machina)
#**.delayWeightReward = 15.2        # weight for throughput vs. delay trade-off

# Servers
**.server[*].numApps = 1
**.server[*].app[*].typename = "TcpSinkApp"

# Routers
**.router1.ppp[*].queue.packetDropped = true
**.router2.ppp[*].queue.recordDrop = true
**.router1.ppp[*].queue.typename = "DropTailQueue"
**.router2.ppp[*].queue.typename = "DropTailQueue"

**.queue.recordStats = true
**.ppp[*].queue.packetCapacity = 40
