[General]
ned-path=/home/cjuknowles/raynet/simlibs/JamesLib/src:/home/cjuknowles/raynet/simlibs/cartpole/src:/home/cjuknowles/raynet/simlibs/RLComponents/src:/home/cjuknowles/inet4.4/src


network = JamesLib.SimpleNet
#debug-on-errors = true

**.tic.sendInitialMessage = true
