
[General]
ned-path = HOME/inet4.5/examples:HOME/inet4.5/showcases:HOME/inet4.5/src:HOME/inet4.5/tests/validation:HOME/inet4.5/tests/networks:HOME/inet4.5/tutorials:HOME/raynet/simlibs/tcpPaced/src:HOME/raynet/simlibs/cubic/src:HOME/raynet/simlibs/RLComponents/src:HOME/raynet/simlibs/Orca/src


check-signals = false
record-eventlog= false
cmdenv-express-mode = true
record-eventlog=false
cmdenv-redirect-output = false
cmdenv-output-file = dctcpLog.txt
#**.client*.tcp.conn-8.cmdenv-log-level = detail
cmdenv-log-prefix = %t | %m |

cmdenv-silent = true


cmdenv-event-banners = false
**.cmdenv-log-level = off

# Orca parameters (I'm not even sure these do anything without some external implementation)
**.minDelay = DELAY_PLACEOLDER


**.**.tcp.conn-*.cwnd:vector(removeRepeats).vector-recording = true
**.**.tcp.conn-*.rtt:vector(removeRepeats).vector-recording = true
**.**.tcp.conn-*.srtt:vector(removeRepeats).vector-recording = true
**.**.tcp.conn-*.throughput:vector(removeRepeats).vector-recording = true
**.**.tcp.conn-*.**.result-recording-modes = vector(removeRepeats)
**.**.queue.queueLength:vector(removeRepeats).vector-recording = true
**.**.queue.queueLength.result-recording-modes = vector(removeRepeats)
**.**.goodput:vector(removeRepeats).vector-recording = true
**.**.goodput.result-recording-modes = vector(removeRepeats)
**.**.bandwidth:vector(removeRepeats).vector-recording = true
**.**.bandwidth.result-recording-modes = vector(removeRepeats)
**.**.mbytesInFlight:vector(removeRepeats).vector-recording = true
**.**.mbytesInFlight.result-recording-modes = vector(removeRepeats)
**.scalar-recording=false
**.vector-recording=true
**.bin-recording=false 

**.numberOfFlows = 1
network = Orca.OrcaNet

# Clients
**.client[*].numApps = 1
**.client[*].app[*].typename  = "TcpSessionApp"
**.client[*].app[*].active = true
**.client[*].app[*].connectAddress = "server["+string(parentIndex())+"]"
**.client[*].app[*].tOpen  = 0.0s
**.client[*].app[*].tSend = 0.0s
**.client[*].app[*].tClose = -1s
**.client[*].app[*].sendBytes = 2MiB

# TCP

# Everyone defaults to standard TCP
**.client[0].tcp.typename = "OrcaTcp"
**.client[0].tcp.tcpAlgorithmClass = "Orca" #Orca


**.tcp.advertisedWindow = 200000000
**.tcp.windowScalingSupport = true
**.tcp.windowScalingFactor = -1
**.tcp.increasedIWEnabled = true
**.tcp.delayedAcksEnabled = false
**.tcp.timestampSupport = true
**.tcp.ecnWillingness = false
**.tcp.nagleEnabled = true
**.tcp.stopOperationTimeout = 4000s
**.tcp.mss = 1448
**.tcp.sackSupport = true

# Aiden variables?
**.additiveIncreasePercent = 0.05
**.eta = 0.95
**.alpha = 0.01
**.fixedAvgRTTVal = 0
**.tcp.initialSsthresh = 5792000

# RLTcp variables?
**.maxWindow = 10              # maximum window size 
**.stateSize = 4               # dimension of the state space
**.maxObsCount = 15                # max number of observations for a single state
**.ewmaWeight = 1.5                # weight for the moving average of state variables (as in Tcp-Ex Machina)
**.delayWeightReward = 15.2        # weight for throughput vs. delay trade-off
**.printDebugMessages = false      # set to true to print debug messages for the CC algorithm
**.maxRLSteps = 5000      # set to true to print debug messages for the CC algorithm (if this is too large, rllib may not report any rewards. Be cautious.)
**.monitorIntervalDuration = 1
debug-on-errors = true

# Servers
**.server[*].numApps = 1
**.server[*].app[*].typename = "TcpSinkApp"
**.server[*].tcp.typename = "TcpPaced"
**.server[*].tcp.tcpAlgorithmClass = "TcpCubic"

# Routers
**.router1.ppp[*].queue.packetDropped = true
**.router2.ppp[*].queue.recordDrop = true
**.router1.ppp[*].queue.typename = "DropTailQueue"
**.router2.ppp[*].queue.typename = "DropTailQueue"
#**.router1.ppp[*].queue.dataCapacity = ORCA_BOTTLENECK_BUFFER_SIZE    # Randomly vary the bottleneck buffer to replicate Orca's training
#**.router1.ppp[*].bitrate = ORCA_BOTTLENECK_BW # formatted like 100Mbps
# **.router2.ppp[*].queue.packetCapacity = ???    # TODO: Figure out the default value, see if it is appropriate

**.queue.recordStats = false
**.ppp[*].queue.packetCapacity = 100
