
[General]
ned-path = HOME/inet4.5/examples:HOME/inet4.5/showcases:HOME/inet4.5/src:HOME/inet4.5/tests/validation:HOME/inet4.5/tests/networks:HOME/inet4.5/tutorials:HOME/raynet/simlibs/tcpPaced/src:HOME/raynet/simlibs/RLComponents/src:HOME/raynet/simlibs/Astrea/src:HOME/raynet/simlibs/Astrea/src/training

# Outputs/verbosity
check-signals = false
record-eventlog= false
cmdenv-express-mode = true
cmdenv-redirect-output = false
cmdenv-log-prefix = %t | %m |
cmdenv-silent = true
cmdenv-event-banners = false
**.cmdenv-log-level = off
**.queue.recordStats = false

# Metrics (for plotting!)
**.scalar-recording=false
**.vector-recording=false
**.bin-recording=false

# Network parameters
network = Astrea.training.AstreaTraining

# Variable network parameters
**.ppp[*].queue.dataCapacity = BOTTLENECK_BUFFER_SIZE # Buffer size
**.bottleneckDatarate = BOTTLENECK_BW
**.bottleneckDelay = BASE_RTT
**.numberOfFlows = NUM_FLOWS

# Astrea uses ground-truth network parameters for training
**.astreaDataCapacity = BOTTLENECK_BUFFER_SIZE
**.astreaBottleneckDatarate = BOTTLENECK_BW
**.astreaBottleneckDelay = BASE_RTT


# Client settings
**.client[*].numApps = 1
**.client[*].app[*].typename  = "TcpSessionApp"
**.client[*].app[*].active = true
**.client[*].app[*].connectAddress = "server["+string(parentIndex())+"]"
**.client[*].app[*].tOpen  = 0.0s
**.client[*].app[*].tSend = 0.0s
**.client[*].app[*].tClose = 0s
**.client[*].app[*].sendBytes = 2GB

# Router/queue settings
**.router1.ppp[0].queue.typename = "DropTailQueue"

# Misc. TCP Settings
**.tcp.mss= 1024
**.tcp.advertisedWindow = 1073741823
**.tcp.limitedTransmitEnabled = false # Need to add the limited transmit check for SACK based fadt recoverty.
**.tcp.windowScalingSupport = true
**.tcp.timestampSupport = true
**.tcp.nagleEnabled = true
**.tcp.sackSupport=true
**.tcp.delayedAcksEnabled = false
**.tcp.increasedIWEnabled = false
**.tcp.dupthresh = 3
**.tcp.max_burst = 100000
**.tcp.initialSsthresh = 102400

# RLTcp variables?
**.maxWindow = 10                       # maximum window size 
**.stateSize = 4                        # dimension of the state space
**.maxObsCount = 15                     # max number of observations for a single state
**.ewmaWeight = 1.5                     # weight for the moving average of state variables (as in Tcp-Ex Machina)


# All agents use Astrea
**.client[*].tcp.typename = "AstreaTcp"
**.client[*].tcp.tcpAlgorithmClass = "Astrea"
**.server[*].tcp.typename = "Tcp"
**.server[*].tcp.tcpAlgorithmClass = "TcpNoCongestionControl"

# Servers
**.server[*].numApps = 1
**.server[*].app[*].typename = "TcpSinkApp"
**.server[*].tcp.typename = "Tcp"
**.server[*].tcp.tcpAlgorithmClass = "TcpNoCongestionControl"

# Astrea Parameters
**.rewardDelayForgiveness = 1.25        # How much delay increases should be forgiven/ignored in reward calculation
**.rewardLossMultiplier = 5             # How strongly loss should affect reward calculation
**.observer.printDebugMessages = false
**.printDebugMessages = false           # set to true to print debug messages for the CC algorithm
**.takeActions = true                  # If false, will stop Astrea from performing actions
**.maxRLSteps = MAX_RL_STEPS            # Steps before a given agent's simulation is reset
**.fixedIntervals = true                # Interval lengths should be fixed
**.fixedIntervalDuration = .03          # Monitor interval duration in seconds. Still used as initial intervalDuration if not using fixed intervals.
debug-on-errors = true
