
[General]
ned-path = HOME/inet4.5/examples:HOME/inet4.5/showcases:HOME/inet4.5/src:HOME/inet4.5/tests/validation:HOME/inet4.5/tests/networks:HOME/inet4.5/tutorials:HOME/raynet/simlibs/tcpPaced/src:HOME/raynet/simlibs/RLComponents/src:HOME/raynet/simlibs/Astrea/src:HOME/raynet/simlibs/Astrea/src/training


check-signals = false
record-eventlog= false
cmdenv-express-mode = true
cmdenv-redirect-output = false
#**.client*.tcp.conn-8.cmdenv-log-level = detail
cmdenv-log-prefix = %t | %m |
# debug = getEnvir()->getConfig()->getAsBool(CFGID_PARSIM_DEBUG);
cmdenv-silent = true


cmdenv-event-banners = false
**.cmdenv-log-level = off

# Orca parameters (I'm not even sure these do anything without some external implementation)

# Hard-coded values are for testing and faster trainingbottleneckLine.datarate = 3Mbps
#bottleneckLine.delay = 1ms
**.ppp[*].queue.dataCapacity = ORCA_BOTTLENECK_BUFFER_SIZE # Buffer size
**.bottleneckDatarate = ORCA_BOTTLENECK_BW
**.bottleneckDelay = ORCA_BASE_RTT

#bottleneckLine.datarate = ORCA_BOTTLENECK_BW
#bottleneckLine.delay = ORCA_BASE_RTT
#**.ppp[*].queue.dataCapacity = ORCA_BOTTLENECK_BUFFER_SIZE
#**.ppp[*].queue.packetCapacity = 100
#**.r1.ppp[*].queue.packetCapacity = 500


#**.**.tcp.conn-*.cwnd:vector(removeRepeats).vector-recording = true
#**.**.tcp.conn-*.rtt:vector(removeRepeats).vector-recording = true
#**.**.tcp.conn-*.srtt:vector(removeRepeats).vector-recording = true
#**.**.tcp.conn-*.throughput:vector(removeRepeats).vector-recording = true
#**.**.tcp.conn-*.**.result-recording-modes = vector(removeRepeats)
#**.**.queue.queueLength:vector(removeRepeats).vector-recording = true
#**.**.queue.queueLength.result-recording-modes = vector(removeRepeats)
#**.**.goodput:vector(removeRepeats).vector-recording = true
#**.**.goodput.result-recording-modes = vector(removeRepeats)
#**.**.bandwidth:vector(removeRepeats).vector-recording = true
#**.**.bandwidth.result-recording-modes = vector(removeRepeats)
#**.**.mbytesInFlight:vector(removeRepeats).vector-recording = true
#**.**.mbytesInFlight.result-recording-modes = vector(removeRepeats)
**.scalar-recording=false
**.vector-recording=false
**.bin-recording=false 

**.numberOfFlows = 2
network = Astrea.training.AstreaTraining

# Clients
**.client[*].numApps = 1
**.client[*].app[*].typename  = "TcpSessionApp"
**.client[*].app[*].active = true
**.client[*].app[*].connectAddress = "server["+string(parentIndex())+"]"
**.client[*].app[*].tOpen  = 0.1s
**.client[*].app[*].tSend = 0.0s
**.client[*].app[*].tClose = 0s
**.client[*].app[*].sendBytes = 2GB

# TCP

# A single agent uses Orca
**.client[*].tcp.typename = "AstreaTcp"
**.client[*].tcp.tcpAlgorithmClass = "Astrea"
**.server[*].tcp.typename = "Tcp"
**.server[*].tcp.tcpAlgorithmClass = "TcpNoCongestionControl"

# Everyone else defaults to standard TCP
#**.client[*].tcp.typename = "TcpPaced"
#**.client[*].tcp.tcpAlgorithmClass = "TcpCubic"

# Servers
**.server[*].numApps = 1
**.server[*].app[*].typename = "TcpSinkApp"
**.server[*].tcp.typename = "TcpPaced"
**.server[*].tcp.tcpAlgorithmClass = "TcpCubic"

# Routers
#**.router1.ppp[*].queue.packetDropped = true
#**.router2.ppp[*].queue.recordDrop = true
**.router1.ppp[*].queue.typename = "DropTailQueue"
**.router2.ppp[*].queue.typename = "DropTailQueue"
#**.router1.ppp[*].queue.dataCapacity = ORCA_BOTTLENECK_BUFFER_SIZE    # Randomly vary the bottleneck buffer to replicate Orca's training
#**.router1.ppp[*].bitrate = ORCA_BOTTLENECK_BW # formatted like 100Mbps
# **.router2.ppp[*].queue.packetCapacity = ???    # TODO: Figure out the default value, see if it is appropriate
**.queue.recordStats = false


# Misc. TCP Settings
**.tcp.mss= 1024
**.tcp.advertisedWindow = 1073741823
**.tcp.limitedTransmitEnabled = false # Need to add the limited transmit check for SACK based fadt recoverty.
**.tcp.windowScalingSupport = true
**.tcp.timestampSupport = true
**.tcp.nagleEnabled = true
**.tcp.sackSupport=true
**.tcp.delayedAcksEnabled = false
**.tcp.increasedIWEnabled = false
**.tcp.dupthresh = 3
**.tcp.max_burst = 100000

# Aiden variables?
**.additiveIncreasePercent = 0.05
**.eta = 0.95
**.alpha = 0.01
**.fixedAvgRTTVal = 0
**.tcp.initialSsthresh = 102400

# RLTcp variables?
**.maxWindow = 10                       # maximum window size 
**.stateSize = 4                        # dimension of the state space
**.maxObsCount = 15                     # max number of observations for a single state
**.ewmaWeight = 1.5                     # weight for the moving average of state variables (as in Tcp-Ex Machina)

# Orca
**.rewardDelayForgiveness = 1.25          # How much delay increases should be forgiven/ignored in reward calculation
**.rewardLossMultiplier = 5             # How strongly loss should affect reward calculation
**.printDebugMessages = true           # set to true to print debug messages for the CC algorithm
**.takeActions = true                  # If false, will stop Orca from performing actions
**.maxRLSteps = MAX_RL_STEPS            # Steps before a given agent's simulation is reset
**.monitorIntervalDuration = 1
debug-on-errors = true


